### ISSUE TITLE
"stop" operation is awaiting instance to start

### ISSUE THREAD

**Issue by isemenko** [Zoomdata/try#10]
› ./try-zoomdata.sh stop
Stopping try-zoomdata_zoomdata-data-writer_1     ... done
Stopping try-zoomdata_zoomdata-web_1             ... done
Stopping try-zoomdata_zoomdata-query-engine_1    ... done
Stopping try-zoomdata_zoomdata-edc-postgresql_1  ... done
Stopping try-zoomdata_zoomdata-edc-apache-solr_1 ... done
Stopping try-zoomdata_zoomdata-edc-rts_1         ... done
Stopping try-zoomdata_zoomdata-postgres_1        ... done
Stopping try-zoomdata_zoomdata-consul_1          ... done
Stopping try-zoomdata_zoomdata-client_1          ... done
Waiting for Zoomdata instance to start. Max 300 seconds
.................................................................................................^C

**Comment by Niyakiy** [comment]
only `.sh` script was affected, `.ps1` already includes the corresponding if statement.
Fixed as of c275c60a8eaf0dd9c
