### ISSUE TITLE
zoomdata-postgres container fails to start in Windows

### ISSUE THREAD

**Issue by dilantpatel-logi** [Zoomdata/try#5]
Per Trevor, fix is to map only 'pgdata' folder to host volume. i.e. update docker-compose.yml for zoomdata-postgres: 

    volumes:
      - ./data/**pgdata**:/var/lib/postgresql/**pgdata**

**Comment by Niyakiy** [comment]
Accordingly, to the official docs for PostgreSQL in Docker (https://hub.docker.com/_/postgres) the way data should be mounted is:
`docker run --name some-postgres -v /my/own/datadir:/var/lib/postgresql/data -d postgres:tag` 
So codebase contains proper right-side of the volume mapping.
What are the issues being experienced by you @dilantpatel-logi?

**Comment by Niyakiy** [comment]
these can be used to overcome the issue. 
https://github.com/docker/for-win/issues/445#issuecomment-405185621
It was tested by me and works fine.

**Comment by dilantpatel-logi** [comment]
Great. Thanks Eugene.
